apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: ci-idea-state
  namespace: default
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: sys-ops-redis-master.sys-ops:6379

